Promise.resolve(3).then((result) => console.log(result));
Promise.reject("Error!").catch((err) => console.log(err));